### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by manwar**
Hi @SysPete 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by racke** [comment]
@manwar Sorry, but the minor fix is drowned into a sea of unrelated changes.

**Comment by manwar** [comment]
OMG, did I do anything wrong?

**Comment by manwar** [comment]
Here is my commit:

       commit 951e2d111a359b252595b84ed8310192550b5cb0
       Author: Mohammad S Anwar <mohammad.anwar@yahoo.com>
       Date:   Mon Oct 22 13:15:21 2018 +0100

       Fixed minor typo in the pod.

       commit 9fe25222991e7cae445d754ec95dcb123cd0762c
       Author: Peter Mottram (SysPete) <peter@sysnix.com>
       Date:   Sun Oct 21 13:51:09 2018 +0200

       bump version and update changes for v3.3.2

**Comment by manwar** [comment]
commit 951e2d111a359b252595b84ed8310192550b5cb0
	Author: Mohammad S Anwar <mohammad.anwar@yahoo.com>
	Date:   Mon Oct 22 13:15:21 2018 +0100
	
		Fixed minor typo in the pod.
	
	diff --git a/lib/Dancer2/Plugin/Passphrase.pm b/lib/Dancer2/Plugin/Passphrase.pm
	index d430392..9b1213a 100644
	--- a/lib/Dancer2/Plugin/Passphrase.pm
	+++ b/lib/Dancer2/Plugin/Passphrase.pm
	@@ -102,7 +102,7 @@ that is suitable for storage in a database.
	
	It returns a Dancer2::Plugin::Passphrase::Hashed object.
	
	-You should store C<$phrase->rfc_2307()> in your database.
	+You should store C<$phrase-E<gt>rfc_2307()> in your database.
	
	Accepts a hashref of options to specify what kind of hash should be 
	generated. All options settable in the config file are valid.
	@@ -128,7 +128,7 @@ So for Bcrypt this might be:
	
		my $phrase = passphrase('my password')->generate(
			{
	-            algorith => 'Bcrypt',
	+            algorithm => 'Bcrypt',
				Bcrypt   => {
					cost => 14,
				}
	@@ -214,7 +214,7 @@ The scheme name can be any of the following, and will always be capitalized
	
	Returns the algorithm name from a C<Dancer2::Plugin::Passphrase> object.
	
	-The algorithm name can be anything that is accepted by C<Digest->new($alg)>
	+The algorithm name can be anything that is accepted by C<Digest-E<gt>new($alg)>
	This includes any modules in the C<Digest::> Namespace

**Comment by racke** [comment]
It looks like that branch where you applied your fixes was **really** stale. So create a new branch from the current master and cherry-pick your commit in that branch. And produce a new PR.

**Comment by manwar** [comment]
@racke if you look at the commit history, my commit is just before the last commit of "master". could it be GitHub is not behaving? It has been on/off since last night.

**Comment by racke** [comment]
Well, the repository aligned with the CPAN code is https://github.com/SysPete/Dancer2-Plugin-Passphrase.

**Comment by SysPete** [comment]
This repo hasn't been the canonical one for a long time as it was maintained in hvoers' repo which no longer exists. Latest changes are in my fork but I will push back to this upstream shortly including changes from latest release this last weekend.

**Comment by SysPete** [comment]
@manwar many thanks for the fix, merged via commit c71f8e7b217bbf9650c36e26fa15d91ddbee17f1. I'll upload a new version shortly.

**Pull request closed without merging**
